#
#
#    CEsvga2 - ChrisEric1 Super Video Graphics Array 2
#    Copyright (C) 2023-2024, Christopher Eric Lentocha
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published
#    by the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

name: Xcode
on: workflow_dispatch
jobs:
 build:
  name: Xcode
  runs-on: macos-12
  steps:
   - name: Checkout
     uses: actions/checkout@v4.1.1
     with:
      clean: 'false'
      sparse-checkout-cone-mode: 'true'
      fetch-depth: '0'
      fetch-tags: 'true'
      show-progress: 'true'
      lfs: 'true'
      submodules: 'true'
      set-safe-directory: 'true'
   - name: Build
     run: xcodebuild build -project="./*.xcodeproj"
   - name: Upload
     uses: actions/upload-artifact@v4.0.0
     with:
      name: Xcode
      path: .
